version: '2.1'

services:

  promociones-db:
    build: ./db
    environment:
      MYSQL_DATABASE: Promociones
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 1234
      DATABASE_HOST: db

  promociones-ms:
    build: .
    environment:
      NODE_ENV: production
      DATABASE_HOST: db
      MYSQL_PORT: 3302
      MYSQL_DATABASE: Promociones
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 1234
    ports:
      - "3004:3000"
    depends_on:
      - promociones-db
    restart: on-failure
